name: Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-5.6-release
          tag: 5.6-RELEASE
  
      - uses: actions/checkout@v2
      - run: swift build
      - run: swift test
